/**
 * Generates public/sitemap.xml from the route registry so it can't drift from
 * the app's real routes or the capability catalogue.
 *
 * Usage: node scripts/gen-sitemap.mjs
 * (runs automatically as part of "build" and "build:ssg")
 */
import { writeFile } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { ROUTE_META, canonicalUrl } from '../src/lib/routes.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'public', 'sitemap.xml');

const lastmod = new Date().toISOString().slice(0, 10);

const body = ROUTE_META.map(({ path, priority, changefreq }) => `  <url>
    <loc>${canonicalUrl(path)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority.toFixed(1)}</priority>
  </url>`).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-sitemap.mjs — do not edit by hand -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

await writeFile(OUT, xml);
console.log(`sitemap.xml written with ${ROUTE_META.length} URLs`);
